###
GET http://localhost:8080/api/v1/menu/pizzas

###
POST http://localhost:8080/api/v1/orders/create
Content-Type: application/json

[
  {
    "code": 1,
    "name": "Margherita",
    "price": "6.00",
    "ingredients": [
      "Mozzarella",
      "Pomodoro",
      "Origano",
      "Basilico",
      "Olio d’oliva"
    ]
  }
]

###
GET http://localhost:8080/api/v1/orders/C001